name: Upload Website

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.21'

    - name: Build wasm file
      run: GOARCH=wasm GOOS=js go build -o build/web/app.wasm ./app

    - name: Build app file
      run: go build -o build/app ./app

    - name: Generate Website
      run: cd build && ./app && rm ./app

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./build/ s3://studybear --delete