# Simple workflow for deploying static content to GitHub Pages
name: Deploy test to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Build wasm file
        run: GOARCH=wasm GOOS=js go build -o build/web/app.wasm ./app

      - name: Build app file
        run: go build -o build/app ./app

      - name: Generate Website
        run: cd build && export READ_KEY=${{ secrets.READ_KEY }} && export GITHUB=TRUE && ./app && rm ./app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1